#!/usr/bin/env python3
"""Remove build paths, customize 'component' field
"""

import traceback
import sys
import os
import re
import util
from util import Column
from util import eprint

msvc = False


def define_component(parts):
    file = parts[Column.FILE].replace("\\", r"/")
    if "include/QtMultimedia" in file:
        return "CsMultimedia"
    if "include/QtCore" in file:
        return "CsCore"
    if "/src/core" in file:
        return "CsCore"
    if "include/QtGui" in file:
        return "CsGui"
    if "/webkit" in file:
        return "webkit"
    if "/WebCore" in file:
        return "WebCore"
    if "/src/gui/" in file:
        return "CsGui"
    if "/src/multimedia/" in file:
        return "multimedia"
    if "/src/network/" in file:
        return "network"
    if "/src/opengl/" in file:
        return "opengl"
    if "/src/plugins/" in file:
        return "plugins"
    if "/src/script/" in file:
        return "script"
    if "/src/svg/" in file:
        return "svg"
    if "/src/xmlpatterns/" in file:
        return "xmlpatterns"
    if "/src/xml/" in file:
        return "xml"
    if "/src/tools/" in file:
        return "tools"
    if "/3rdparty" in file:
        return "3rdparty"
    if "/MSVC" in file:
        return "MSVC"
    return ""


def get_substring_end_position(needle, haystack):
    position = haystack.find(needle)
    if position == -1:
        return 0
    return position + len(needle)


def remove_pattern(input_string, pattern):
    # Search for the pattern in the input string
    match = re.search(pattern, input_string)

    # If the pattern is found, return the end-position
    if match:
        _start, end_index = match.span()
        return end_index
    # If the pattern is not found, return -1
    return -1

# notice [[marker]] is prefixed to indicate the path needs to be fixed
# by create_default_link()


def remove_build_path(parts):
    file = parts[Column.FILE]
    uniform_filepath = file.replace("\\", r"/")
    build_path = "/include/Qt"
    position = uniform_filepath.find(build_path)
    if position != -1:
        return "_buildpath_" + file[position:]

    build_path = "/privateinclude/Qt"
    position = uniform_filepath.find(build_path)
    if position != -1:
        return "_buildpath_" + file[position:]

    source_path = "copperspice/src/"
    position = uniform_filepath.find(source_path)
    if position != -1:
        position += len("copperspice")
        return "[[marker]]" + file[position:]

    end_position = remove_pattern(uniform_filepath, r".*Program\sFiles/Microsoft.*/\d+/\w+/")
    if end_position != -1:
        return file[end_position:]

    # remove X:\
    if re.search(r'\w:\\', file):
        return file[3:]

    return file


def create_default_link(parts):
    file = parts[Column.FILE]
    name, linenumber = file.split(":")

    url = util.urljoin("[[permalink-prefix]]", name.replace("\\", "/"))
    links = util.create_link(3, url)

    # check for positive line number
    if str.isdigit(linenumber):
        links = util.create_link(3, url + "#L" + str(linenumber))
    return links


def customize(line):
    global msvc
    parts = line.strip().split("|")
    parts[Column.COMPONENT] = define_component(parts)
    if msvc:
        parts[Column.FILE] = remove_build_path(parts).replace("/", "\\")
    else:
        parts[Column.FILE] = remove_build_path(parts)

    file = parts[Column.FILE]
    if file.startswith("[[marker]]"):
        length = len("[[marker]]")
        parts[Column.FILE] = file[length:]
        parts[Column.LINK] = parts[Column.LINK] + create_default_link(parts)
    util.write_structured_line(parts)


def show_usage():
    eprint("Usage: " + os.path.basename(__file__) + " [/msvc]")
    eprint("   /msvc transform unix paths generated by lexers/parsers also to windows style paths")
    eprint("   will customize structured CSV, according to user-specific rulesm, see customize()")


def main():
    global msvc
    if len(sys.argv) > 1:
        msvc = True

    for line in sys.stdin:
        customize(line)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        raise
    except SystemExit:
        raise
    except BrokenPipeError:   # still makes piping into 'head -n' work nicely
        sys.exit(0)
    except:
        info = traceback.format_exc()
        eprint(info)
        show_usage()
        sys.exit(1)
